// <auto-generated />
using System;
using BarbecueRestApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarbecueRestApi.Migrations
{
    [DbContext(typeof(BarbecueRestApiContext))]
    [Migration("20200824231235_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BarbecueRestApi.Models.Establishment", b =>
                {
                    b.Property<int>("EstablishmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("DrinkPrice");

                    b.Property<double>("FoodPrice");

                    b.Property<string>("NameEstablishment");

                    b.HasKey("EstablishmentId");

                    b.ToTable("Establishment");
                });

            modelBuilder.Entity("BarbecueRestApi.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Canceled");

                    b.Property<double>("DrinkPrice");

                    b.Property<int>("EstablishmentId");

                    b.Property<double>("FoodPrice");

                    b.Property<bool>("GoingToDrink");

                    b.Property<bool>("GoingToEat");

                    b.Property<bool>("IsGuest");

                    b.Property<string>("NameParticipant");

                    b.Property<int?>("ParticipantReferenceId");

                    b.HasKey("ParticipantId");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("BarbecueRestApi.Models.Participant", b =>
                {
                    b.HasOne("BarbecueRestApi.Models.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
